In [1]:
import pandas as pd
import numpy as np

In [7]:
path='../datasets/LUN/fulltrain.csv'
dataset=pd.read_csv(path,header=None)

In [8]:
dataset.head(5)

   0                                                  1
0  1  A little less than a decade ago, hockey fans w...
1  1  The writers of the HBO series The Sopranos too...
2  1  Despite claims from the TV news outlet to offe...
3  1  After receiving 'subpar' service and experienc...
4  1  After watching his beloved Seattle Mariners pr...

In [11]:
cols=('category','content')

In [14]:
dataset.columns=cols
dataset.head()
type(dataset['category'][0])

numpy.int64

In [19]:
# for category !=4, define the fake label
def set_label(category):
    if category!=4:
        return 'fake'
    else:
        return 'real'
dataset['labels']=dataset['category'].apply(lambda x :set_label(x))

In [20]:
dataset.head()

   category                                            content labels
0         1  A little less than a decade ago, hockey fans w...   fake
1         1  The writers of the HBO series The Sopranos too...   fake
2         1  Despite claims from the TV news outlet to offe...   fake
3         1  After receiving 'subpar' service and experienc...   fake
4         1  After watching his beloved Seattle Mariners pr...   fake

In [21]:
dataset.to_csv('lun.csv')