In [1]:
import pandas as pd
import numpy as np

In [2]:
path = 'lun.csv'
df = pd.read_csv(path)

In [3]:
df.head(5)

,Unnamed: 0,og_label,text,label
0,0,1,The writers of the HBO series The Sopranos too...,0
1,1,1,Despite claims from the TV news outlet to offe...,0
2,2,1,After receiving 'subpar' service and experienc...,0
3,3,1,After watching his beloved Seattle Mariners pr...,0
4,4,1,"At a cafeteria-table press conference Monday, ...",0

In [4]:
len(df)

48853

In [5]:
# get satire and reliable class
df = df[~df.og_label.isin([2, 3])]
df.head(5)
len(df)

24041

In [22]:
# from sklearn.model_selection import train_test_split
# train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
# train_df.to_csv('lun_train_new.csv',index=False)
# test_df.to_csv('lun_test_new.csv',index=False)

In [9]:
df.to_csv('lun_train_comparenet.csv', index=False)

In [41]:
df_test = pd.read_csv('balancedtest.csv')

In [42]:
df_test.head(5)

   og_label                                               text
0         1  When so many actors seem content to churn out ...
1         1   In what football insiders are calling an unex...
2         1  In a freak accident following Game 3 of the N....
3         1  North Koreas official news agency announced to...
4         1  The former Alaska Governor Sarah Palin would b...

In [48]:
# get satire and reliable class
df_test = df_test[~df_test.og_label.isin([2, 3])]

1500

In [49]:
# get only fake and real label
def labeled(x):
    if x == 4:
        return 1
    else:
        return 0


df_test['label'] = df_test['og_label'].apply(labeled)

In [50]:
df_test['label']

0       0
1       0
2       0
3       0
4       0
       ..
2995    1
2996    1
2997    1
2998    1
2999    1
Name: label, Length: 1500, dtype: int64

In [51]:
df_test.to_csv('lun_test_comparenet.csv', index=False)

In [35]:
train=len(df)

In [36]:
test=len(df_test)

In [37]:
valid=360

In [38]:
import math
lcm=(train*test*valid)//math.gcd(train,math.gcd(test,valid))
train_ratio=lcm//train
test_ratio=lcm//test
valid_ratio=lcm//valid
print(train_ratio,test_ratio,valid_ratio)

540000 8654760 36061500

In [39]:
print(train)
print(test)

24041
1500

In [40]:
import math

a = 24041
b = 1500
c = 360

lcm = (a * b * c) // math.gcd(a, math.gcd(b, c))

a_ratio = lcm // a
b_ratio = lcm // b
c_ratio = lcm // c

print(f'{a}:{b}:{c} = {a_ratio}:{b_ratio}:{c_ratio}')

24041:1500:360 = 540000:8654760:36061500