In [1]:
raw_data_path = 'real_and_fake.csv'
destination_folder = '../datasets/real_and_fake_new/'
train_test_ratio = 0.10
train_valid_ratio = 0.80
# trim the words in the news
first_n_words = 512

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [19]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('../model_files/bert-base-uncased')


def trim_string(x):
    x = x.split(maxsplit=first_n_words)
    x = ' '.join(x[:first_n_words])
    return x


def get_attention_mask(x):
    return tokenizer(x, add_special_tokens=True, return_attention_mask=True, return_tensors='pt')['attention_mask'].tolist()

In [5]:
  # Read raw data
df_raw = pd.read_csv(raw_data_path)

# Prepare columns
df_raw['label'] = (df_raw['label'] == 'FAKE').astype('int')
df_raw = df_raw.reindex(columns=[ 'title', 'text', 'label'])

# Drop rows with empty text
df_raw.drop(df_raw[df_raw.text.str.len() < 5].index, inplace=True)

# Trim text and titletext to first_n_words
df_raw['label']=df_raw['label']
df_raw['text'] = df_raw['text']
df_raw.head()

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",1
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,1
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,0
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",1
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,0

In [6]:
df_raw.to_csv(destination_folder+'/'+'train.csv',index=False)
# # Split according to label
# df_real = df_raw[df_raw['label'] == 0]
# df_fake = df_raw[df_raw['label'] == 1]
#
# # Train-test split
# df_real_full_train, df_real_test = train_test_split(df_real, train_size=train_test_ratio, random_state=1)
# df_fake_full_train, df_fake_test = train_test_split(df_fake, train_size=train_test_ratio, random_state=1)
#
# # Train-valid split
# df_real_train, df_real_valid = train_test_split(df_real_full_train, train_size=train_valid_ratio, random_state=1)
# df_fake_train, df_fake_valid = train_test_split(df_fake_full_train, train_size=train_valid_ratio, random_state=1)
#
# # Concatenate splits of different labels
# df_train = pd.concat([df_real_train, df_fake_train], ignore_index=True, sort=False)
# df_valid = pd.concat([df_real_valid, df_fake_valid], ignore_index=True, sort=False)
# df_test = pd.concat([df_real_test, df_fake_test], ignore_index=True, sort=False)
#
# # Write preprocessed data
# df_train.to_csv(destination_folder + '/train.csv', index=False)
# df_valid.to_csv(destination_folder + '/valid.csv', index=False)
# df_test.to_csv(destination_folder + '/test.csv', index=False)

In [22]:
df_raw['label'][0]

AttributeError: 'list' object has no attribute 'type'

In [9]:
len(df_valid)

127

In [10]:
len(df_test)

5670

In [11]:
import torch

In [12]:
print(torch.cuda.is_available())

True

In [13]:
df_train.head()

,label,title,text,titletext,attention_mask
0,0,Obamacare's unlikely No. 1 city,"Killing Obama administration rules, dismantlin...",Obamacare's unlikely No. 1 city. Killing Obama...,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
1,0,New York restores order for 2016 front-runners,Hillary Clinton and Donald Trump scored resoun...,New York restores order for 2016 front-runners...,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
2,0,These political scientists may have just disco...,There's a lot of disgust in America with polit...,These political scientists may have just disco...,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
3,0,"Hillary supporters: We're excited, too, but al...",Trump and Sanders get all the attention for th...,"Hillary supporters: We're excited, too, but al...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
4,0,Hung jury in Jodi Arias sentencing phase remov...,The jury in the Jodi Arias case tasked with de...,Hung jury in Jodi Arias sentencing phase remov...,"[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."