In [1]:
import pandas as pd
path='../datasets/SLN/test.xlsx'

In [2]:
df=pd.read_excel(path)

In [4]:
df.head()

,Satirical =1 Legitimate=0,Article Headline,Full Text,Domain,Subtopic,Source,Issue Date,URL,Access Date
0,0,Jeb Bush’s Cerebral Debate Style Faces a Test:...,"On the debate stage, Jeb Bush has committed th...",Politics/Civics,Elections/Debates,New York Times,09-15-2015,http://www.nytimes.com/2015/09/14/us/politics/...,09-29-2015
1,0,"Carly Fiorina, Gaining in Polls, Moves to Secu...",WASHINGTON — When Carly Fiorina found herself ...,Politics/Civics,Elections/Debates,New York Times,08-27-2015,http://www.nytimes.com/2015/08/28/us/politics/...,09-29-2015
2,0,Mike Huckabee Offers 6 Percent Economic Growth...,DES MOINES – As the first of more than a dozen...,Politics/Civics,Elections/Debates,New York Times,08-13-2015,http://www.nytimes.com/politics/first-draft/20...,09-29-2015
3,0,Scott Walker Ends His 2016\nPresidential Run,"Updated, 9:59 p.m. | Gov. Scott Walker of Wisc...",Politics/Civics,Elections/Debates,New York Times,09-21-2015,http://www.nytimes.com/politics/first-draft/20...,09-29-2015
4,0,"Hillary Clinton to Show More Humor and Heart, ...",There will be no more flip jokes about her pri...,Politics/Civics,Elections/Debates,New York Times,09-07-2015,http://www.nytimes.com/2015/09/08/us/politics/...,09-29-2015

In [9]:
df=df.drop(columns=['Domain','Subtopic','Source','Issue Date ','URL','Access Date'])

In [10]:
df = df.rename(columns={'Satirical =1 Legitimate=0': 'label','Article Headline':'title','Full Text ':'text'})

In [11]:
df.head()

,label,title,text
0,0,Jeb Bush’s Cerebral Debate Style Faces a Test:...,"On the debate stage, Jeb Bush has committed th..."
1,0,"Carly Fiorina, Gaining in Polls, Moves to Secu...",WASHINGTON — When Carly Fiorina found herself ...
2,0,Mike Huckabee Offers 6 Percent Economic Growth...,DES MOINES – As the first of more than a dozen...
3,0,Scott Walker Ends His 2016\nPresidential Run,"Updated, 9:59 p.m. | Gov. Scott Walker of Wisc..."
4,0,"Hillary Clinton to Show More Humor and Heart, ...",There will be no more flip jokes about her pri...

In [14]:
value_map = {0: 1, 1: 0}

df['label']=df['label'].map(value_map)
df.head()

,label,title,text
0,1,Jeb Bush’s Cerebral Debate Style Faces a Test:...,"On the debate stage, Jeb Bush has committed th..."
1,1,"Carly Fiorina, Gaining in Polls, Moves to Secu...",WASHINGTON — When Carly Fiorina found herself ...
2,1,Mike Huckabee Offers 6 Percent Economic Growth...,DES MOINES – As the first of more than a dozen...
3,1,Scott Walker Ends His 2016\nPresidential Run,"Updated, 9:59 p.m. | Gov. Scott Walker of Wisc..."
4,1,"Hillary Clinton to Show More Humor and Heart, ...",There will be no more flip jokes about her pri...

In [17]:
df.to_csv('../datasets/SLN/sln_full.csv',index=False)